-- DROP USER DSY2201 CASCADE;
-- 1. Nos aseguramos de estar en la raíz
ALTER SESSION SET CONTAINER = CDB$ROOT;

-- 2. Borramos el usuario mal creado para evitar conflictos
DROP USER DSY2201 CASCADE;

-- 3. Creamos el usuario oficial (Common User)
CREATE USER C##DSY2201 IDENTIFIED BY "DSY2201_$"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- 4. Asignamos los permisos
GRANT CREATE SESSION, RESOURCE TO C##DSY2201;
ALTER USER C##DSY2201 DEFAULT ROLE RESOURCE;